# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/indicator_hub/all/indicator_hub.rbi
#
# indicator_hub-0.1.0

module IndicatorHub
end
class IndicatorHub::TALibAdapter
  def self.available?; end
  def self.sma(data, period); end
end
